name: develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: yarn install
        run: yarn install

      - name: Next.js build
        run: yarn build

      - name: Run jest
        run: yarn test
